[package]
name = "seldom_pixel"
version = "0.6.1"
edition = "2021"
categories = ["game-development"]
description = "Bevy plugin for limited color palette pixel art games"
exclude = ["assets/"]
keywords = ["gamedev", "bevy", "graphics", "gui", "2d"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Seldom-SE/seldom_pixel"

[features]
line = ["dep:line_drawing"]
nav = ["dep:seldom_map_nav"]
particle = ["dep:bevy_turborand"]
state = ["dep:seldom_state"]

[dependencies]
anyhow = "1.0"
event-listener = "5.3"
serde = "1.0"
line_drawing = { version = "1.0", optional = true }
seldom_fn_plugin = "0.6.0"
seldom_singleton = "0.1.0"
bevy_turborand = { version = "0.8.1", optional = true }
seldom_state = { version = "0.10.0", optional = true }
seldom_map_nav = { version = "0.6.0", optional = true }
seldom_pixel_macros = { version = "0.1.0", path = "macros" }

[dependencies.bevy]
version = "0.13.0"
default-features = false
features = ["bevy_asset", "bevy_core_pipeline", "bevy_render", "bevy_sprite"]

[dev-dependencies]
bevy = { version = "0.13.0", features = ["png"] }
leafwing-input-manager = "0.13.3"
rand = "0.8.5"
seldom_state = { version = "0.10.0", features = ["leafwing_input"] }

[[example]]
name = "line"
required-features = ["line"]

[[example]]
name = "particles"
required-features = ["particle"]

[[example]]
name = "state"
required-features = ["state"]

[package.metadata.docs.rs]
all-features = true
